server:
  port: 8088
logging:
  level:
    root: info

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: consumer
  protocol:
    port: 20881
  threads: 100
  timeout: 3000
  cluster: failover
  retries: 0